#!/bin/bash

#
# Run from within a directory to generate technical metadata reports for specified image files using Exiftool
#

# generate list of JPG files in current directory
# WORKS #ls -1 *.* > filelist.txt

ls -1 *.{jpg,gif,tif,pdf,jpf,jp2,png,dicom,xcf,tiff,jpeg} > filelist.txt

#
# TEST #while read line; do echo "$line"; done < filelist.txt

while read line; do exiftool $line > $line.exiftool.txt; done < filelist.txt
