#!/usr/bin/python
# -*- coding: utf-8 -*-
#import codecs
import os, sys
import re
import time
#Feeding in a list of file-extentions -- one for each occurance of a file-type in a file system, produce a list of file types (file extentions) with no duplicates.
#grep --only-matching -E "[a-z,A-Z,0-9]+\.[a-z,A-Z,0-9][a-z,A-Z,0-9][a-z,A-Z,0-9]\n" fulllist.txt > list_of_file_extentions.txt ; grep -o '[a-z,A-Z,0-9]\.[a-z,A-Z][a-z,A-Z][a-z,A-Z]$' list_of_extensions.txt | sed 's/[a-z,A-Z,0-9]\.//' | sed 's/\s$//' > list.txt

sourceFile = "list.txt"
directory = "/home/comstock/Documents/python"
inputFilename = directory + "/" + sourceFile

print "DEBUG: Input filename = " + inputFilename
out = open ("fileTypesOut.txt",'w')
gaggle ={""}

with open(inputFilename,'r') as jello:
    for line in jello:
        # print line
        # if re.search("\.[a-z,A-Z,0-9][a-z,A-Z,0-9][a-z,A-Z,0-9]\s", f): print line
        # if re.match('\.[a-z,A-z][a-z,A-z][a-z,A-z]', line): print out.write(line)
#         if re.match(".\w\w\w", line): print line
        # if re.findall(".\w\w\w", line): print line
        line = line.rstrip()
        gaggle.add(line)        
out.write('\n'.join(gaggle))
